
//
// Basic -- 4 fundsp builtin oscillators (sin/tri/square/saw), independently
// level-mixed. A test voice, not a real patch.
//
// The whole skeleton (View, view(), fields()/apply(), apply_cc(), new(),
// AudioNode + Voice impls) is generated by #[derive(Voice)] -- see
// voice-macro/src/lib.rs. Only the struct declaration + the DSP body in
// impl VoiceDsp::render are hand-written.
//

use fundsp::prelude64::*;
use zgicabra_voice_macro::Voice;

use super::stutter::stutter;
use super::signal::SharedSignal;
use super::voice::{Voice, VoiceDsp, ThumpMod};

#[derive(Clone, Voice)]
#[voice(index = 2, label = "Basic")]
pub struct BasicVoice {
    #[node(init = sine())]     sin:    An<Sine<f64>>,
    #[node(init = triangle())] tri:    An<WaveSynth<U1>>,
    #[node(init = square())]   square: An<WaveSynth<U1>>,
    #[node(init = saw())]      saw:    An<WaveSynth<U1>>,

    #[node(init = stutter())]   stutter: An<Unit<U1, U1>>,

    #[input(cc = "1", range = 0.0..1.0,  set = |v| v,           default = 0.25)] pub sin_level:     Shared,
    #[input(cc = "2", range = 0.0..1.0,  set = |v| v,           default = 0.25)] pub tri_level:     Shared,
    #[input(cc = "3", range = 0.0..1.0,  set = |v| v,           default = 0.25)] pub square_level:  Shared,
    #[input(cc = "4", range = 0.0..1.0,  set = |v| v,           default = 0.25)] pub saw_level:     Shared,
    #[input(cc = "5", range = 1.0..1.0,  set = |v| v,           default = 0.25)] pub stutter_level: Shared,
    #[input(cc = "6", range = 1.0..10.0, set = |v| 1.0 + v*9.0, default = 1.0)]  pub saturation:    Shared,

    thump: ThumpMod,
    sig:   SharedSignal,
}

impl VoiceDsp for BasicVoice {
    fn render (&mut self, freq: f32, _thump_mult: f32) -> Frame<f32, U2> {
        let mono = self.sin.filter_mono(freq)    * self.sin_level.value()
                 + self.tri.filter_mono(freq)    * self.tri_level.value()
                 + self.square.filter_mono(freq) * self.square_level.value()
                 + self.saw.filter_mono(freq)    * self.saw_level.value()
                 + self.stutter.filter_mono(freq) * self.stutter_level.value();

        let mono = (mono * self.saturation.value()).tanh() * self.sig.env.value();

        Frame::from([mono, mono])
    }
}
