
//
// Voice: one sound generator. Every Voice is wired in parallel into Engine,
// held as `Box<dyn Voice>` in a plain homogeneous array (see engine.rs) --
// Voice is deliberately its own small object-safe trait (no fundsp
// AudioNode/AudioUnit supertrait: those carry associated consts/types that
// rule out trait objects) so the array needs no per-concrete-type dispatch.
// Engine is what decides whether a given voice is the selected one on each
// tick, calling tick() for real if so and on_silence() otherwise -- a
// Voice's own tick() always renders, it has no idea whether it's selected.
//
// Each concrete Voice owns its tunable params directly, as `Shared` cells
// (for anything outside the audio thread needs to read) or plain fields (for
// anything nobody outside the audio thread touches). The audio thread is the
// only writer of every per-voice value -- tuning happens live via MIDI CC
// (apply_cc below, see src/audio/cc_input.rs) -- so there's no separate
// external-facing handle type to keep in sync.
//
// Knob selection (distinct from CC1-4, the global filter/width/fuzz/thump
// mapping in audio/mod.rs's build_stream): every #[knob] field a voice
// declares is collected, in struct declaration order, into that voice's
// ordered knob list (KNOB_NAMES/KNOB_RANGES, generated by #[derive(Voice)]).
// One CC (5) moves `selected_knob` to an index into that list; another (6)
// writes the currently-selected knob's value -- see build_stream for the
// exact CC -> method mapping. This replaces the old direct cc="N" per-field
// binding: an 8-knob controller reaches every knob a voice has, however many
// there are, without needing one physical knob per param.
//

use fundsp::prelude64::*;

// Implemented for every generated *View (see #[derive(Voice)]'s
// gen_view_impl) -- lets code that only needs get/set-by-name access to a
// voice's live params (persisting them to disk) work the same regardless of
// which concrete voice's View it's holding, without knowing that View's own
// field names.
pub trait ViewFields {
    fn fields (&self) -> Vec<(&'static str, f32)>;
    fn apply (&self, fields: &[(String, f32)]);
}

pub trait Voice: Send {
    // Slot this voice occupies in Engine::voices / Handles::voice_selected --
    // fixed per concrete type (see #[voice(index = ..)]).
    fn index (&self) -> usize;
    fn name (&self) -> &'static str;
    // One sample, mono freq in, (left, right) out. Always renders -- the
    // caller (Engine) is the one that knows whether this voice is selected.
    fn tick (&mut self, freq: f32) -> (f32, f32);
    fn set_sample_rate (&mut self, sample_rate: f64);
    // Called once per cpal callback chunk, before that block's tick()
    // calls -- extension point for a voice that needs block-driven
    // inference (a NamStage internally, say): fill a scratch buffer across
    // tick() calls, run it here.
    fn on_block_start (&mut self, _block_len: usize) {}
    // Called by Engine instead of tick() when this voice is NOT selected --
    // default no-op. Override only if a voice must keep book-keeping
    // running while gated out (GrowlVoice advances its NAM scratch cursor
    // here so a mid-block voice switch stays aligned).
    fn on_silence (&mut self) {}

    // Ordered #[knob] list (see the module doc above) -- fixed per concrete
    // type, generated by #[derive(Voice)].
    fn knob_count (&self) -> usize;
    fn knob_name (&self, index: usize) -> &'static str;
    fn knob_range (&self, index: usize) -> (f32, f32);
    fn knob_value (&self, index: usize) -> f32;

    // Index into the knob list the next CC6-style value message targets.
    // Clamped to knob_count() - 1; changing it resets this voice's
    // KnobPickup so the newly-selected knob requires a fresh pickup.
    fn selected_knob (&self) -> usize;
    fn set_selected_knob (&mut self, index: usize);

    // Sets the value at `index` from a raw 0..1 CC level, gated through this
    // voice's KnobPickup (soft takeover) -- a no-op until the incoming raw
    // level crosses the knob's current normalized position.
    fn set_knob_value (&mut self, index: usize, raw: f32);
}

// Absolute-pot soft takeover for one physical CC channel (CC6/CC8): a knob
// only starts tracking the incoming raw 0..1 level once it's crossed the
// knob's current value, so switching `selected_knob` never causes the
// newly-selected param to jump to wherever the pot happened to be left.
// `last_raw` is a sentinel (-1.0, below any real CC level) until the first
// message arrives, so a single message can never look like a crossing.
#[derive(Clone)]
pub struct KnobPickup {
    last_raw:  f32,
    picked_up: bool,
}

impl KnobPickup {
    pub fn new () -> KnobPickup {
        KnobPickup { last_raw: -1.0, picked_up: false }
    }

    // Call whenever the selected knob changes -- the physical pot's last
    // known position is kept, but the new knob must be crossed again.
    pub fn reset (&mut self) {
        self.picked_up = false;
    }

    // `target_norm` is the selected knob's current value, normalized 0..1.
    // Returns Some(raw) once picked up (caller should apply it), None while
    // still waiting for the pot to cross the knob's position.
    pub fn update (&mut self, raw: f32, target_norm: f32) -> Option<f32> {
        if !self.picked_up && self.last_raw >= 0.0 {
            let crossed = (self.last_raw <= target_norm && raw >= target_norm)
                       || (self.last_raw >= target_norm && raw <= target_norm);
            if crossed { self.picked_up = true; }
        }
        self.last_raw = raw;
        if self.picked_up { Some(raw) } else { None }
    }
}

// The DSP half of a voice, hand-written by the author. #[derive(Voice)]
// generates the Voice::tick wrapper (thump application) and calls render()
// with a freq that's already thump-applied -- render() is the old per-sample
// tick body, minus the boilerplate prologue.
pub trait VoiceDsp {
    // `freq` is already thump-applied; `thump_mult` is the raw pitch
    // multiplier thump contributed this sample (1.0 at rest), handed over
    // for voices that surface it as telemetry (GrowlVoice's freq_mult_live).
    // Engine does not gate a voice's output by the note envelope -- render()
    // is responsible for reading self.sig.env itself and shaping its own
    // output by it (see any voice's render() for the convention). This is
    // what lets a voice like ReeseVoice deliberately leave part of its
    // signal (its feedback loop) ungated, while every other voice just
    // multiplies its whole output by env like Engine used to do for them.
    fn render (&mut self, freq: f32, thump_mult: f32) -> Frame<f32, U2>;
    // Block-driven inference hook (a NamStage internally, say) -- default
    // no-op; the generated Voice::on_block_start delegates here.
    fn on_block_start (&mut self, _block_len: usize) {}
    // Called by the generated Voice::on_silence -- default no-op. Override
    // only if a voice must keep book-keeping running while gated out
    // (GrowlVoice advances its NAM scratch cursor here so a mid-block voice
    // switch stays aligned).
    fn on_silence (&mut self) {}
    // Called at the end of the generated Voice::set_sample_rate (after it
    // forwards to every #[node] field + thump) -- default no-op. Override for
    // a voice that caches the sample rate in a plain field (SwarmVoice).
    fn on_set_sample_rate (&mut self, _sample_rate: f64) {}
}

// Pitch-thump envelope: each voice owns its own copy so `thump` is a signal
// a voice reacts to, not a pre-bent freq it's handed.
#[derive(Clone)]
pub(super) struct ThumpMod {
    trigger: Shared,
    peak:    Shared,
    decay:   Shared,
    last_trigger:    f32,
    elapsed_samples: f32,
    sample_rate:     f32,
}

impl ThumpMod {
    pub(super) fn new (trigger: Shared, peak: Shared, decay: Shared) -> ThumpMod {
        ThumpMod { trigger, peak, decay, last_trigger: 0.0, elapsed_samples: 0.0, sample_rate: DEFAULT_SR as f32 }
    }

    pub(super) fn set_sample_rate (&mut self, sample_rate: f64) {
        self.sample_rate = sample_rate as f32;
    }

    // Returns a pitch multiplier to apply to this voice's freq -- 1.0 at
    // rest, bumped up (decaying over thump_decay seconds) each time
    // thump_trigger changes, scaled by thump_peak and the live signal_thump.
    pub(super) fn tick (&mut self, signal_thump: f32) -> f32 {
        let trigger = self.trigger.value();
        if trigger != self.last_trigger {
            self.last_trigger = trigger;
            self.elapsed_samples = 0.0;
        }

        let t = self.elapsed_samples / self.sample_rate;
        self.elapsed_samples += 1.0;

        let decay_sec  = self.decay.value().max(0.001);
        let pitch_bump = self.peak.value() * signal_thump;
        let decay = (-5.0 * t / decay_sec).exp();
        1.0 + decay * pitch_bump
    }
}

